import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { motion, AnimatePresence, AnimateSharedLayout } from "framer-motion";
import { useEffect, useState } from "react";
import { createClient } from "contentful";
import GitHubIcon from "@mui/icons-material/GitHub";
import ArrowForwardIosIcon from "@mui/icons-material/ArrowForwardIos";
import ArrowBackIosIcon from "@mui/icons-material/ArrowBackIos";
import { ReactTerminal } from "react-terminal";
import { useRouter } from "next/router";
import TelegramIcon from "@mui/icons-material/Telegram";
import EmailIcon from '@mui/icons-material/Email';
import Link from "next/link";

export async function getStaticProps() {
  const client = createClient({
    space: process.env.Contentful_SpaceId,
    accessToken: process.env.Contentful_AccessToken,
  });
  const res = await client.getEntries({
    content_type: "test",
  });
  return {
    props: {
      Projects: res.items,
    },
  };
}

export default function Home({ Projects }) {
  const [visibility1, setVisibility1] = useState("none");
  const [visibility2, setVisibility2] = useState("none");
  const [Project, setSelectedProject] = useState(null);
  const [Gallery, setSelectedGallery] = useState(null);
  const [Index, setIndex] = useState(0);
  const [Loaded, setLoaded] = useState(false);
  const router = useRouter();

  useEffect(() => {
    setLoaded(true);
  });
  const Welcome = <p>type "hello" to start</p>;
  const commands = {
    projects: () =>
      Projects.map((project, index) => (
        <p key={index}>
          {index + 1} {project.fields.title}
        </p>
      )),
    project: (index) => setSelectedProject(Projects[index - 1]),
    about: () => setVisibility2("flex"),
    hello: () => setVisibility1("flex"),
    blog: () => router.push("/blog"),
  };
  const handleNext = () => {
    if (Gallery) {
      const Length = Gallery.length - 1;
      if (Index < Length) {
        setIndex(Index + 1);
      } else {
        setIndex(0);
      }
    }
  };
  const handlePrevious = () => {
    if (Index > 0) {
      setIndex(Index - 1);
    }
  };
  const handleClose = () => {
    setSelectedGallery(null);
    setIndex(0);
  };

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.HomeContainer}>
          <AnimatePresence>
            {Project && (
              <motion.div
                drag
                className={styles.ProductWindow}
                layoutId={Project.sys.id}
                style={{ paddingBottom: "50px" }}
              >
                <motion.h2 className={styles.windowTitle}>
                  {Project.fields.title}
                </motion.h2>
                <motion.img
                  onClick={() => setSelectedGallery(Project.fields.gallery)}
                  className={styles.image}
                  src={Project.fields.thumbnail.fields.file.url}
                />
                <motion.h5 className={styles.description}>
                  {Project.fields.description}
                </motion.h5>
                <motion.button
                  className={styles.closeButton}
                  onClick={() => setSelectedProject(null)}
                />
                <motion.div className={styles.links}>
                  <a className={styles.github} href={Project.fields.githubLink}>
                    <GitHubIcon />
                  </a>
                  {Project.fields.demoLink && (
                    <motion.a
                      className={styles.demo}
                      href={Project.fields.demoLink}
                    >
                      Live Demo
                    </motion.a>
                  )}
                </motion.div>
              </motion.div>
            )}
          </AnimatePresence>
          <AnimatePresence>
            {Gallery && (
              <motion.div drag className={styles.ProductWindow}>
                <motion.div
                  style={{
                    width: "100%",
                    height: "100%",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                  }}
                >
                  <img
                    src={Gallery[Index].fields.file.url}
                    style={{ width: "90%", borderRadius: "20px" }}
                  />
                </motion.div>
                <button
                  className={styles.closeButton}
                  onClick={() => handleClose()}
                />
                <button
                  onClick={() => handleNext()}
                  style={{
                    position: "absolute",
                    color: "white",
                    border: "none",
                    backgroundColor: "transparent",
                    right: "0",
                    top: "50%",
                  }}
                >
                  <ArrowForwardIosIcon />
                </button>
                <button
                  onClick={() => handlePrevious()}
                  style={{
                    position: "absolute",
                    color: "white",
                    border: "none",
                    backgroundColor: "transparent",
                    left: "0",
                    top: "50%",
                  }}
                >
                  <ArrowBackIosIcon />
                </button>
              </motion.div>
            )}
          </AnimatePresence>
          {Loaded && (
            <motion.div className={styles.TerminalContainer} drag>
              <ReactTerminal
                commands={commands}
                themes={{
                  myTheme: {
                    themeBGColor: " #1d1e22",
                    themeColor: "#B6EADA",
                    themeToolbarColor: "#03001C",
                  },
                }}
                theme='myTheme'
                welcomeMessage={Welcome}
              />
            </motion.div>
          )}
          <AnimatePresence>
            <motion.div
              style={{ display: visibility1 }}
              drag
              className={styles.window}

            >
              <button
                className={styles.closeButton}
                onClick={() => setVisibility1("none")}
              />
              <h1 style={{ color: "#9f8198", margin: "3%" }}>Hello,</h1>
              <p className={styles.Text1}>
                I am amine an Algerian Full-Stack web developer, <br />
                with a passion for creating dynamic and engaging web
                applications.
              </p>
              <p className={styles.Text2}>

                type "about" to learn more about me.
                <br />
                type "projects" to see my projects, then type "project number"
                to see that project. you can also click on the picture to see
                more pictures. and type "blog" to see to go to my blog.<br />Enjoy.
              </p>
              <div>
                <h3 className={styles.Text5}>Welcome to my website :) </h3>
              </div>
            </motion.div>
          </AnimatePresence>
          <AnimatePresence>
            <motion.div
              style={{ display: visibility2, top: "20vh" }}
              className={styles.window}
              drag
            >
              <button
                className={styles.closeButton}
                onClick={() => setVisibility2("none")}
              />
              <p className={styles.Text3}>
                I am a freelance web developer using MERN stack and nextjs, my
                expertise lies in developing scalable, responsive, engaging and
                robust web applications that ensure the best user experience and
                client satisfaction. <br />
              </p>
              <ul style={{ alignSelf: "flex-start" }}>
                <p className={styles.Text3}>
                  The main technologies i use:</p>
                <li>React and React Native</li>
                <li>NextJS</li>
                <li>ExpressJS</li>
                <li>Mongodb</li>
                <li>different CMS and Headless CMS</li>
              </ul>
              <p
                style={{
                  alignSelf: "center",
                  color: "#de7300",
                  margin: "2%",
                  fontSize: "1em",
                }}
              >
                If you`re looking for a web developer who can help bring your
                vision to life, feel free to get in touch!
              </p>
              <div style={{ display: 'flex' }}>
                <a style={{ textDecoration: 'none', marginRight: '20px' }} href='https://t.me/vergil_am'><TelegramIcon /></a>
                <a style={{ textDecoration: 'none', color: 'white' }} href="mailto:olamine336@gmail.com"><EmailIcon /></a>
              </div>
            </motion.div>
          </AnimatePresence>
        </div>
      </main>
    </>
  );
}
